resolver: nightly-2021-09-18
system-ghc: true
allow-different-user: true
packages:
  - .
extra-deps:
  - github: tkachuk-labs/persistent-migration
    commit: 0e40b397fa1042e117ec0809d5715b7aa1e636f6
  - github: tkachuk-labs/bitfinex-client
    commit: 3d26b5335d8c151d3ccc093de12afc65e90b6d90
